---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-kube-metrics-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-kube-metrics-monitor
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-kube-metrics-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-kube-metrics-monitor
subjects:
  - kind: ServiceAccount
    name: test-kube-metrics-monitor
---
apiVersion: v1
kind: Pod
metadata:
  name: test-kube-metrics-reporter
  labels:
    app: test-kube-metrics-reporter
spec:
  serviceAccountName: test-kube-metrics-monitor
  containers:
    - name: test-kube-metrics-reporter
      image: kube-metrics-reporter
      env:
        - name: INTERVAL
          value: "10s"
        - name: INCLUDE_LABELS
          value: "true"
        - name: NAMESPACE
          value: "default"
